### PR TITLE
Bump handlebars from 4.1.2 to 4.5.3

### PR DESCRIPTION
**Pull request by AlexZhenWang**

### CODE REVIEW

**Comment by benxgao** [comment]
@AlexZhenWang Conflicts to be resolved

**Comment by AlexZhenWang** [comment]
> @AlexZhenWang Conflicts to be resolved

yeah, I see. It's strange, my branch is from the latest master... let me push again..

**Comment by benxgao** [comment]
@AlexZhenWang We are working in `develop` branch, which contains all latest PRs, we have not add it in contribution doc yet~ So you need to branch off develop branch

**Comment by AlexZhenWang** [comment]
> @AlexZhenWang We are working in `develop` branch, which contains all latest PRs, we have not added it in contribution doc yet~ So you need to branch from develop branch

Ah that's the reason! Thanks Ben

**Comment by benxgao** [comment]
@AlexZhenWang Can you `yarn install` locally and push up the yarn.lock changes as well?

**Comment by benxgao** [comment]
@AlexZhenWang Actually, `handlebars` seems not being used, we could remove it directly? Can you yarn install locally and push up the yarn.lock changes as well?

**Comment by AlexZhenWang** [comment]
> @AlexZhenWang Actually, `handlebars` seems not being used, we could remove it directly? Can you yarn install locally and push up the yarn.lock changes as well?

em.. I see `handlebars` is used 
image

There is no change needed for yarn.lock because seems like this branch is already using handlebar 4.5.3. So I just change the package.json.
image

**Pull request merged**
