### PR TITLE
Add types and update derive

### PR DESCRIPTION
**Pull request by KarishmaBothara**

### CODE REVIEW

**Comment by KarishmaBothara** [comment]
This branch brings all the changes from master to develop branch (eg - optimised derived queries)
Things to do
1. Add mintAdditional test
2. Fix https://github.com/cennznet/api.js/issues/415

**Review by ken-centrality — APPROVED** [review]
LGTM! One thing I noticed is it's missing the `mintAdditional` test. Are we gonna do it a bit later?

**Comment by ken-centrality** [comment]
Also, `tokenInfo.ts` missing `attributes` data that querying from `api.query.nft.seriesAttributes(tokenId.collectionId, tokenId.seriesId)`

```
@@ -31,29 +32,32 @@
 export function tokenInfo(instanceId: string, api: ApiInterfaceRx) {
   return (tokenId: TokenId | EnhancedTokenId): Observable<DeriveTokenInfo> => {
     tokenId = new EnhancedTokenId(api.registry, tokenId);
-    return api.query.nft
-      .tokenOwner([tokenId.collectionId.toNumber(), tokenId.seriesId.toNumber()], tokenId.serialNumber.toNumber())
-      .pipe(
-        switchMap(
-          (owner): Observable<DeriveTokenInfo> => {
-            return of(
-              new Object({
-                owner: owner.toString(),
-                tokenId: tokenId as EnhancedTokenId,
-              }) as DeriveTokenInfo
-            );
-          }
-        )
-      );
+
+    return combineLatest([
+      api.query.nft.tokenOwner([tokenId.collectionId, tokenId.seriesId], tokenId.serialNumber),
+      api.query.nft.seriesAttributes(tokenId.collectionId, tokenId.seriesId),
+    ]).pipe(
+      switchMap(
+        ([owner, attributes]): Observable<DeriveTokenInfo> => {
+          return of(
+            new Object({
+              owner: owner.toString(),
+              attributes: attributes,
+              tokenId: tokenId as EnhancedTokenId,
+            }) as DeriveTokenInfo
+          );
+        }
+      )
+    );
   };
 }
```

**Comment by KarishmaBothara** [comment]
this PR also fixes the warning we currently have with 2.1.0-alpha.0

2022-02-03 23:05:18 PORTABLEREGISTRY: Unable to determine runtime Call type, cannot inspect sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic
2022-02-03 23:05:18 PORTABLEREGISTRY: Unable to determine runtime Event type, cannot inspect frame_system::EventRecord

have updated the polkadot to 7.7 to fix this - https://github.com/polkadot-js/api/issues/4526

**Review by ken-centrality — APPROVED** [review]
LGTM

**Pull request merged**
