### PR TITLE
Updated azalea metadata

### PR DESCRIPTION
**Pull request by KarishmaBothara**
Updated static metadata for azalea

### CODE REVIEW

**Comment by alexsednz** [comment]
Does this mean we now need to publish a new version of the API package again?

**Comment by KarishmaBothara** [comment]
> Does this mean we now need to publish a new version of the API package again?

Not really.. It can wait, nothing will break... Sylo will use the slim metadata, so it won't impact them. Only anyone using the cennznet/api directly, it might slow down, cause it will fetch metadata and then use..

**Comment by alexsednz** [comment]
Please do not merge as I have already cherry-picked your commits here to my branch. Thanks.

**Comment by alexsednz** [comment]
Now we can safely close it as I merged the commits already.

**Pull request closed without merging**
