### PR TITLE
Chore/patch balance derive

### PR DESCRIPTION
**Pull request by KarishmaBothara**
For Sylo to use new API with Azalea rv36, need to patch balances as a derived module as it does not exist till rv36..
May be after upgrade, we can remove changes in this PR..
I am still thinking of any possible way to add test...

### CODE REVIEW

**Comment by alexsednz** [comment]
I guess your change here is now mixed with your other PR: https://github.com/cennznet/api.js/pull/233, can you please separate them?

**Comment by KarishmaBothara** [comment]
> I guess your change here is now mixed with your other PR: #233, can you please separate them?

done.. created PR against update_dependencies branch, so that only changes related to this PR are visible..

**Review by alexsednz — APPROVED** [review]

**Comment by KarishmaBothara** [comment]
The only test that doesn't work is the subscribe events from archive node - as it stopped working since last night..

**Comment by holygits** [comment]
can we close this one?

**Comment by KarishmaBothara** [comment]
> can we close this one?

yes... will close it for now..

**Pull request closed without merging**
